### ISSUE TITLE
Cannot read property 'kthid' of null på Spexmästare

### ISSUE THREAD

**Issue by macfeaster** [datasektionen/dfunkt#10]
Trodde först att det var för att posten är vakant men det finns andra poster som hanterar det.
Får `Error: Cannot read property 'kthid' of null` på http://dfunkt.froyo.datasektionen.se/position/spexmastare

**Comment by JSimo** [comment]
Fixat.  Fanns en del trasigt data från importen till databasen från gamla dfunkt.

``` SQL
DELETE FROM "Mandates" where "UserId" is null
```
