### ISSUE TITLE
Posts change names sometimes, and therefore identifiers

### ISSUE THREAD

**Issue by JSimo** [datasektionen/dfunkt#11]
Maybe what is unique needs to be changed...

Changes to post that have been done:
d-smf -> d-ssf 
d-sfor -> d-nok
diu -> isc (Identifier not changed in database yet due to being used by skywhale)

**Comment by LudwikJaniuk** [comment]
I'll take a look later today. Are we using them as unique identifiers somehow? Aren't we using IDs or something?

**Comment by JSimo** [comment]
Example ".../position/kassor", but a change of these urls does not cause any issues for us. Yes, id exists, it should probably be exposed for the role in the api and an api endpoint where you can use the id should be added. In most cases it is fine to use the identifiers as they very rarely changes.
