### ISSUE TITLE
Talk to the permission system

### ISSUE THREAD

**Issue by JSimo** [datasektionen/dfunkt#12]
Time to abandon the local admin thingy. We can probably leave it behind, but should also start talking to pls and use that to determine what permissions a user has. Most likely checking if a user is admin for dfunkt or not is what is needed.  
(probably should check: http://pls.froyo.datasektionen.se/api/user/jsimo/dfunkt/admin, where you can replace jsimo with any kthid)

**Comment by LudwikJaniuk** [comment]
Do we want this change in a place like the `requireadmin` helper? Or rather just use pls on endpoints like `make-admin` and then go with the old `admin` field?

**Comment by JSimo** [comment]
Probably easiest to just change it in the requireadmin helper for now? And just check if either is set to admin.

**Comment by LudwikJaniuk** [comment]
Faster to check on the db tho. Could maybe do it when creating user?

**Comment by JSimo** [comment]
Of course that is faster but does not seem like a good solution. Pls exist to manage permissions, I think we should move away from keeping any kind of permanent permissions local. Like in the future removing the admin attribute is probably good.

**Comment by LudwikJaniuk** [comment]
Ok, yeah it's good so that pls can for example revoke a permission. Will do
it that way.

**Comment by LudwikJaniuk** [comment]
And here we are, still using local admin. Oh well ;)
