### ISSUE TITLE
Personsidor

### ISSUE THREAD

**Issue by ghost** [datasektionen/dfunkt#14]
Det vore nice att ha personsidor för de som är dFunk, så man kan se deras nuvarande och tidigare funktionärsposter på samma sida.

**Comment by JSimo** [comment]
Finns. http://dfunkt.froyo.datasektionen.se/user/pernyb

**Comment by LudwikJaniuk** [comment]
Ja, men länkar vi till dem nånstans?

**Comment by ghost** [comment]
Tack. Använde https://dfunkt.datasektionen.se.

**Comment by JSimo** [comment]
@LudwikJaniuk Nja, de som har en post har ett klickbart namn, men har den personen ingen roll så måste man veta att den sidan finns.
