### ISSUE TITLE
No Link in user lookup

### ISSUE THREAD

**Issue by bullfest** [datasektionen/dfunkt#18]
I user lookup så kan man klicka på användare man hittar, men de gör typ inget vettigt, vore fett om de länkade till användarsidor där man kan se vad en person har gjort.

![image](https://cloud.githubusercontent.com/assets/4342153/23968060/a9a6f06a-09c1-11e7-9718-af3bae72a06e.png)

**Comment by LudwikJaniuk** [comment]
Det låter ju som en cool feature, jag ske se vad som går att göras. Feel free att pinga här om jag skulle glömma bort efter några dagar.

**Comment by LudwikJaniuk** [comment]
Nja, om man klickar på någons namn kommer man till hans/hennes sida på dFunkt, men jag kan väl hålla med om att den informationen inte är sådär jättevärdefull. Är det detta du syftar på? Har du nån speciell idé till vad som skulle vara relevant att länka till?

**Comment by bullfest** [comment]
Syftar alltså på denna sida:
https://dfunkt.datasektionen.se/kthpeople
De borde länka till personsidorna, t.ex. 
https://dfunkt.datasektionen.se/user/viklu

**Comment by LudwikJaniuk** [comment]
Jaha, därifrån. Ok, jag det ser ut som en smart sak att göra. Fixar vid närmsta tillfälle. Tack för tipset.

**Comment by macfeaster** [comment]
Bump :smile:  @LudwikJaniuk @JSimo ?

**Comment by JSimo** [comment]
Håller på och skriver om hela frontend + delar av backend. Tänker mig att detta löser sig när det är klart.
~~Borde ha det klart om max 1-2 veckor.~~
(inklusive saker så som pls integration m.m.)

**Comment by LudwikJaniuk** [comment]
Oh, nice

**Comment by bullfest** [comment]
@JSimo Bump? :smile:

**Comment by JSimo** [comment]
Yea, behövde vara lite helt ledig så tog sommarlov, sorry about that. Typ det som är kvar:
- login/pls, påbörjad
- admin sidor, ej påbörjad (kräver login/pls)
- förbättrad zfinger sök, ej påbörjad. 

Kan inte utlova något, men ska börja kolla på det igen mot slutet av augusti.
(Nuvarande kod: https://github.com/JSimo/dfunkt-wip)

**Comment by LudwikJaniuk** [comment]
Jag tog och implementerade det i senaste committet iaf. Det var ju en one-liner egentligen. @JSimo Hur var det vi deployade nu igen?

**Comment by bullfest** [comment]
@LudwikJaniuk Om du har rättigheter borde det vara `git push dokku@sips.datasektionen.se:dfunkt master`

**Comment by LudwikJaniuk** [comment]
Ok då gör jag det idag nån gång

**Comment by LudwikJaniuk** [comment]
It is done.

**Comment by bullfest** [comment]
Användarsöken när man ska skapa nya mandat är också en länk nu, och går alltså inte att klicka på (då den hoppar) :1st_place_medal: 

![image](https://user-images.githubusercontent.com/4342153/30122752-e8adfb1c-932f-11e7-9d45-dfa19330d755.png)

**Comment by LudwikJaniuk** [comment]
Fixat

**Comment by bullfest** [comment]
Woho! <3
