### ISSUE TITLE
Perhaps use LDAP through zfinger

### ISSUE THREAD

**Issue by addreas** [datasektionen/dfunkt#2]
The api for zfinger has some possibly useful endpoints:
`https://zfinger.datasektionen.se/users/Jesper%20Simonsson`
`https://zfinger.datasektionen.se/user/jsimo`

This api might also move to a separate service in the future.

**Comment by LudwikJaniuk** [comment]
This is a very useful feature. Some others in line first tho, but it's coming.

**Comment by LudwikJaniuk** [comment]
Uhm, how does zfinger actually work? It seems that the search is not exhaustive - `https://zfinger.datasektionen.se/users/Simonsson` doesn't even return the `jsimo` user.

**Comment by addreas** [comment]
Currently it makes three searches, one for exact uid, one for partial uid and one for partial name. Each limited to 10 results. So theoretically there can be no more than 30 results, or 21 because searches for exact uid would only ever return one result. It also seems like the oldest users get returned first which makes the problem more noticeable.

Even using paged results the LDAP server returns at most 1000 results, and then it takes forever as well. I have planed to improve this somehow, but don't currently know how...

**Comment by LudwikJaniuk** [comment]
Is zfinger a project we have control over and can contribute to? I hope we can improve it, because we sure are using it. This feature was just implemented :)
