### ISSUE TITLE
Går inte att skapa nya mandat

### ISSUE THREAD

**Issue by bullfest** [datasektionen/dfunkt#20]
Dfunkt börjar bli jättebroken just nu, går inte att skapa nya mandat alls.
Beror troligtvis på förändringar i zfinger och den tidigare nämnda buggen som introducerades i #18 
Vore toknajs att få det här fix då många av våra system bygger på information från dfunkt

**Comment by LudwikJaniuk** [comment]
Okej, dags att jobba bort den här stora backloggen av issues på dfunkt alltså.

**Comment by bullfest** [comment]
Alltså är typ bara den här som faktiskt är viktig :stuck_out_tongue:

**Comment by LudwikJaniuk** [comment]
Yeah, zfingers API hade ändrats, inte konstigt att det fuckade. Nu är det iaf åtgärdat, så search funkar igen. Ska kolla på att skapa mandat nu.

**Comment by LudwikJaniuk** [comment]
Okeeeeej, nu fattar jag, eftersom users blev länkar så kan man nu inte selecta dem i mandatskapandet. FIxar dirr.

**Comment by LudwikJaniuk** [comment]
@Plongy Fixade det nu, är det löst nu? Frågar ifall det var nåt annat broken med mandate creation.

**Comment by LudwikJaniuk** [comment]
Och nu är länk-funktionaliteten tillbaka i lookup. Säg till om det skulle visa sig att det ofrtfrande inte funkar, det funkar lokalt, men jag är inte admin så kan inte kolla online.

**Comment by bullfest** [comment]
Verkar fungera toppen! Tack :)
