### ISSUE TITLE
Topplista

### ISSUE THREAD

**Issue by amaberg** [datasektionen/dfunkt#31]
Jag tycker att det vore roligt att  ha en topplista på dfunkt över de personer som varit förtroendevalda i flest antal dagar (för att vi ska kunna se hur långt Douglas är före alla andra 😄), liknande den  på  cashflow

**Comment by foodelevator** [comment]
(Och självklart ska dagar räknas flera gånger om man innehar flera poster samtidigt!)

**Comment by Adasjo** [comment]
Detta finns nu!
