### ISSUE TITLE
Some API calls do not work.

### ISSUE THREAD

**Issue by crystopherross** [datasektionen/dfunkt#44]
More specifically these
![Screenshot from 2024-10-03 21-25-24](https://github.com/user-attachments/assets/1a7438ed-3ecb-43cd-bc29-9865ce207d30)
Example, from 
https://dfunkt.datasektionen.se/api/users
we have
![image](https://github.com/user-attachments/assets/7de3c07b-33c0-4bea-96c6-859d4b77eae5)
So for instance
https://dfunkt.datasektionen.se/api/users/robertwb
Should result in a successful call but I get
![image](https://github.com/user-attachments/assets/a928d050-1efd-4f4e-81af-d63946cadc05)
Which should not happen. I checked that the rest of the calls in the list of the first image do not work. The rest of the calls (those not included) seem to work fine.

**Comment by crystopherross** [comment]
This was why, misspelling in the README
/home/c/w/cwmr/Pictures/Screenshot from 2024-10-03 21-38-20.tif

**Comment by Benjaneb** [comment]
It seems this was fixed
